"""new migration

Revision ID: 06cea11e9d67
Revises: fde236c711bd
Create Date: 2024-07-25 01:58:08.542119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '06cea11e9d67'
down_revision: Union[str, None] = 'fde236c711bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('chunks', 'report_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'report_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('chunks', 'session_id')
    # ### end Alembic commands ###
